CREATE TABLE IF NOT EXISTS ingredients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  formal_name TEXT NOT NULL,
  common_name TEXT,
  last_updated TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS tags (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT
);

CREATE TABLE IF NOT EXISTS ingredient_tags (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_id INTEGER NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
  tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  CONSTRAINT ingredient_tags_unique_idx UNIQUE (ingredient_id, tag_id)
);

CREATE INDEX IF NOT EXISTS ingredient_tags_ingredient_id_idx ON ingredient_tags (ingredient_id);
CREATE INDEX IF NOT EXISTS ingredient_tags_tag_id_idx ON ingredient_tags (tag_id);

CREATE TABLE IF NOT EXISTS descriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_id INTEGER NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
  description_short TEXT,
  description_long TEXT
);

CREATE INDEX IF NOT EXISTS descriptions_ingredient_id_idx ON descriptions (ingredient_id);

CREATE TABLE IF NOT EXISTS research (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_link BOOLEAN NOT NULL DEFAULT FALSE,
  last_checked TEXT,
  link TEXT,
  document JSONB,
  summary TEXT
);

CREATE TABLE IF NOT EXISTS determinations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_id INTEGER NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
  confidence TEXT NOT NULL,
  text TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS determinations_ingredient_id_idx ON determinations (ingredient_id);

CREATE TABLE IF NOT EXISTS ingredient_research (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_id INTEGER NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
  research_id INTEGER NOT NULL REFERENCES research(id) ON DELETE CASCADE,
  CONSTRAINT ing_res_unique_idx UNIQUE (ingredient_id, research_id)
);

CREATE INDEX IF NOT EXISTS ing_res_ingredient_id_idx ON ingredient_research (ingredient_id);
CREATE INDEX IF NOT EXISTS ing_res_research_id_idx ON ingredient_research (research_id);

CREATE INDEX IF NOT EXISTS ingredients_search_idx ON ingredients USING GIN (
  to_tsvector('simple', coalesce(formal_name, '') || ' ' || coalesce(common_name, ''))
);

CREATE INDEX IF NOT EXISTS research_summary_search_idx ON research USING GIN (
  to_tsvector('simple', coalesce(summary, ''))
);